Switch from basic authentication to jwt authentication
standupman/standupman pull request #19
Opened 2022-03-12 22:14 UTC by Green-Ranger11

2022-03-15 22:44 UTC, Fenn-CS requested changes
Please take out all linting changes and linter introduction to seperate pr, and leave only jwt updates here!

Thank you! :)

2022-03-15 22:44 UTC, nfebe commented on .eslintrc.json
> +{
There's an issue for this, you want to take this linting update to its own PR.

2022-03-15 22:44 UTC, Fenn-CS commented on Controllers/AuthenticationController.js
> +    User.findOne({ email }).then((foundUser) => {
`foundUser` => `user`

2022-03-15 22:44 UTC, Fenn-CS commented on Controllers/PublicController.js
> +  },
Do linting fixes in the issue that adds the linter updates.

2022-03-15 22:44 UTC, Fenn-CS commented on Controllers/StandUpController.js
> +import StandUp from '../Models/StandUp';
Same here for this linting changes

2022-03-15 22:51 UTC, Fenn-CS requested changes
Looks good! Please, adjust minor change.

2022-03-15 22:51 UTC, Fenn-CS commented on .env.example
> +API_KEY=super_secret_key
JWT_SECRET_KEY

2022-03-17 21:41 UTC, Green-Ranger11 commented
Hi @Fenn-CS sorry to ping in case you are busy but just wanted to ask for your review again.

2022-03-23 09:57 UTC, Fenn-CS approved these changes

2022-03-23 09:59 UTC, merged

2022-03-23 09:59 UTC, Fenn-CS commented
Hello @Green-Ranger11, sorry for the delays! Merged. Thank you :)